[[projects]]
name = "Touch Typer"
image = "TouchTyper"
link = "https://github.com/kochie/touch-type"
content = "A new way to learn touch typing on any platform."
# grid = ["row-span-2", "col-span-2"]

[[projects]]
name = "me.kochie.io"
image = "MeKochieIo"
link = "https://me.kochie.io"
content = "My personal website."

[[projects]]
name = "kochie.space"
image = "KochieSpace"
link = "https://kochie.space"
content = "Some cool content about the fully sick project"

[[projects]]
name = "Web Development - The Right Way"
image = "Halo"
link = "https://google.com"
content = "Some cool content about the fully sick project"

[[projects]]
name = "Contact Tracing"
image = "Halo"
link = "https://ct.vercel.app"
content = "Technical demo for contract tracing at large scale"
# grid = ["row-span-2"]

[[projects]]
name = "blog.kochie.io"
image = "BlogKochieIo"
link = "https://blog.kochie.io"
content = "My blog about webdev, science, and engineering"
# grid = ["row-span-2", "col-span-2"]

[[projects]]
name = "3Body"
image = "ThreeBody"
link = "https://3body.vercel.app"
content = "A n-Body simulator running in 3d on the web browser using webgl."

[[projects]]
name = "CF-AST"
image = "Halo"
link = "https://github.com/kochie/cfast"
content = "CloudFormation Abstract Syntax Tree"
